# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1564, 961)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("QMenu::item:selected {\n"
"    background-color: rgb(210,210,210);  /* 鼠标悬停或选中时的颜色 */\n"
"    color: rgb(0,0,0)\n"
"}\n"
"\n"
"QMenu::item:pressed {\n"
"    background-color: rgb(170,170,170);  /* 按下时的颜色（更深） */\n"
"\n"
"    color: rgb(0,0,0)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(2, 2, 2, 2)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ControlStrip1 = QtWidgets.QWidget(self.centralwidget)
        self.ControlStrip1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ControlStrip1.setObjectName("ControlStrip1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ControlStrip1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.ControlStrip1)
        self.widget.setStyleSheet("background-color: rgb(43, 87, 154);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(10, 10, 12, 0)
        self.horizontalLayout.setSpacing(40)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"            background-color: rgb(235, 235, 235);\n"
"            color: rgb(45, 92, 163);\n"
"            border: None;\n"
"            padding: 8px 15px;\n"
"            font: 12pt \"Noto Sans\";\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    background-color: rgb(43, 87, 154);\n"
"    color: #ffffff;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_2:hover{\n"
"    background-color: #274f8b;\n"
"}\n"
"#pushButton_2:pressed {\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(45, 92, 163);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
"    background-color: rgb(43, 87, 154);\n"
"    color: #ffffff;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_3:hover{\n"
"    background-color: #274f8b;\n"
"}\n"
"#pushButton_3:pressed {\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(45, 92, 163);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
"    background-color: rgb(43, 87, 154);\n"
"    color: #ffffff;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_4:hover{\n"
"    background-color: #274f8b;\n"
"}\n"
"#pushButton_4:pressed {\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(45, 92, 163);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
"    background-color: rgb(43, 87, 154);\n"
"    color: #ffffff;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_5:hover{\n"
"    background-color: #274f8b;\n"
"}\n"
"#pushButton_5:pressed {\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(45, 92, 163);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(100, 40))
        self.pushButton_6.setBaseSize(QtCore.QSize(40, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("#pushButton_6{\n"
"    background-color: rgb(43, 87, 154);\n"
"    color: #ffffff;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_6:hover{\n"
"    background-color: #274f8b;\n"
"}\n"
"#pushButton_6:pressed {\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(45, 92, 163);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.pushButton_14 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("#pushButton_14{\n"
"    background-color: rgb(43, 87, 154);\n"
"    color: #ffffff;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_14:hover{\n"
"    background-color: #274f8b;\n"
"}\n"
"#pushButton_14:pressed {\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(45, 92, 163);\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout.addWidget(self.pushButton_14)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(7, 1)
        self.gridLayout_4.addWidget(self.widget, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.ControlStrip1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(11)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(300, 20))
        self.stackedWidget.setStyleSheet("\n"
"background-color: rgb(235, 235, 235);")
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setMidLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setMinimumSize(QtCore.QSize(0, 40))
        self.page.setObjectName("page")
        self.gridLayout = QtWidgets.QGridLayout(self.page)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(28, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(37)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_23 = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("#pushButton_23{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_23:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_23:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_3.addWidget(self.pushButton_23)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.pushButton_24 = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("#pushButton_24{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_24:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_24:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_3.addWidget(self.pushButton_24)
        spacerItem2 = QtWidgets.QSpacerItem(16, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButton_25 = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("#pushButton_25{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_25:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_25:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_3.addWidget(self.pushButton_25)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setMinimumSize(QtCore.QSize(0, 40))
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(27, -1, -1, -1)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("#pushButton_7{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_7:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_7:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        spacerItem4 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.pushButton_8 = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("#pushButton_8{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_8:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_8:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        spacerItem5 = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.pushButton_9 = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("#pushButton_9{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_9:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_9:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_6.addWidget(self.pushButton_9)
        spacerItem6 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.pushButton_10 = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("#pushButton_10{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_10:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_10:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_6.addWidget(self.pushButton_10)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setMinimumSize(QtCore.QSize(0, 40))
        self.page_3.setObjectName("page_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(26, -1, -1, -1)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_11 = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("#pushButton_11{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_11:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_11:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_7.addWidget(self.pushButton_11)
        spacerItem8 = QtWidgets.QSpacerItem(71, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.pushButton_12 = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("#pushButton_12{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_12:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_12:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        spacerItem9 = QtWidgets.QSpacerItem(38, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.pushButton_13 = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("#pushButton_13{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_13:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_13:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_7.addWidget(self.pushButton_13)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem10, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setMinimumSize(QtCore.QSize(0, 40))
        self.page_8.setObjectName("page_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_8)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(29, -1, -1, -1)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_15 = QtWidgets.QPushButton(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("#pushButton_15{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_15:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_15:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_8.addWidget(self.pushButton_15)
        spacerItem11 = QtWidgets.QSpacerItem(69, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.pushButton_16 = QtWidgets.QPushButton(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("#pushButton_16{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_16:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_16:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.horizontalLayout_8.addWidget(self.pushButton_16)
        spacerItem12 = QtWidgets.QSpacerItem(41, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.pushButton_22 = QtWidgets.QPushButton(self.page_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("#pushButton_22{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_22:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_22:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_8.addWidget(self.pushButton_22)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.gridLayout_7.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_8)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setMinimumSize(QtCore.QSize(0, 40))
        self.page_4.setObjectName("page_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(7, -1, -1, -1)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_19 = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("#pushButton_19{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_19:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_19:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_9.addWidget(self.pushButton_19)
        spacerItem14 = QtWidgets.QSpacerItem(49, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem14)
        self.pushButton_20 = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("#pushButton_20{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_20:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_20:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_9.addWidget(self.pushButton_20)
        spacerItem15 = QtWidgets.QSpacerItem(64, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem15)
        self.pushButton_21 = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("#pushButton_21{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_21:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_21:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout_9.addWidget(self.pushButton_21)
        spacerItem16 = QtWidgets.QSpacerItem(57, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.pushButton_26 = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("#pushButton_26{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_26:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_26:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_9.addWidget(self.pushButton_26)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem17)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setMinimumSize(QtCore.QSize(0, 40))
        self.page_5.setObjectName("page_5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_15.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_15.setSpacing(0)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(33, -1, -1, -1)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_42 = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_42.sizePolicy().hasHeightForWidth())
        self.pushButton_42.setSizePolicy(sizePolicy)
        self.pushButton_42.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setStyleSheet("#pushButton_42{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_42:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_42:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_42.setObjectName("pushButton_42")
        self.horizontalLayout_19.addWidget(self.pushButton_42)
        spacerItem18 = QtWidgets.QSpacerItem(66, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem18)
        self.pushButton_43 = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_43.sizePolicy().hasHeightForWidth())
        self.pushButton_43.setSizePolicy(sizePolicy)
        self.pushButton_43.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setStyleSheet("#pushButton_43{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_43:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_43:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_19.addWidget(self.pushButton_43)
        spacerItem19 = QtWidgets.QSpacerItem(42, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem19)
        self.pushButton_44 = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_44.sizePolicy().hasHeightForWidth())
        self.pushButton_44.setSizePolicy(sizePolicy)
        self.pushButton_44.setMinimumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setStyleSheet("#pushButton_44{\n"
"    background-color: rgb(235, 235, 235);\n"
"    color: rgb(0, 0, 0);;\n"
"    border: None;\n"
"    padding: 8px 15px;\n"
"    font: 12pt \"Noto Sans\";\n"
"}\n"
"#pushButton_44:hover{\n"
"    background-color: rgb(190, 190, 190);\n"
"}\n"
"#pushButton_44:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"    color: rgb(240, 240, 240);\n"
"}")
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_19.addWidget(self.pushButton_44)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem20)
        self.gridLayout_15.addLayout(self.horizontalLayout_19, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_5)
        self.horizontalLayout_11.addWidget(self.stackedWidget)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.verticalLayout_5.addLayout(self.verticalLayout_11)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("#pushButton_17{\n"
"    background-color: rgb(230,230, 230);\n"
"    border: None;\n"
"}\n"
"#pushButton_17:hover{\n"
"    background-color: rgb(220, 220, 220);\n"
"}\n"
"#pushButton_17:pressed {\n"
"    background-color: rgb(190, 190, 190);\n"
"}")
        self.pushButton_17.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icon/Icons/left (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_17.setIcon(icon)
        self.pushButton_17.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_17.setObjectName("pushButton_17")
        self.horizontalLayout_5.addWidget(self.pushButton_17)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(300, 60))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Noto Sans\";\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"border: none;\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(300, 60))
        self.label_4.setMaximumSize(QtCore.QSize(500, 80))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Noto Sans\";\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setStyleSheet("background-color: rgb(230, 230, 230);\n"
"")
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"font: 12pt \"Noto Sans\";")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_6.addWidget(self.label_12)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setStyleSheet("font: 12pt \"Noto Sans\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.spinBox = QtWidgets.QSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.spinBox.setFont(font)
        self.spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("    font: 12pt \"Noto Sans\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.spinBox_2 = QtWidgets.QSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_2.sizePolicy().hasHeightForWidth())
        self.spinBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout_2.addWidget(self.spinBox_2)
        self.label_8 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("    font: 12pt \"Noto Sans\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.spinBox_3 = QtWidgets.QSpinBox(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_3.sizePolicy().hasHeightForWidth())
        self.spinBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_3.setMaximum(255)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout_2.addWidget(self.spinBox_3)
        self.horizontalLayout_2.setStretch(5, 2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("font: 12pt \"Noto Sans\";")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("    font: 12pt \"Noto Sans\";")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.doubleSpinBox.setFont(font)
        self.doubleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox.setDecimals(1)
        self.doubleSpinBox.setMaximum(360.0)
        self.doubleSpinBox.setSingleStep(0.1)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox)
        self.label_10 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("    font: 12pt \"Noto Sans\";")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(11)
        self.doubleSpinBox_2.setFont(font)
        self.doubleSpinBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.doubleSpinBox_2.setDecimals(1)
        self.doubleSpinBox_2.setMaximum(360.0)
        self.doubleSpinBox_2.setSingleStep(0.1)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_4.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.checkBox = QtWidgets.QCheckBox(self.widget1)
        self.checkBox.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.checkBox.setFont(font)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setStyleSheet("    font: 12pt \"Noto Sans\";")
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_6.addWidget(self.checkBox)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget1)
        self.verticalLayout_3.setStretch(1, 2)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.setStretch(1, 2)
        self.horizontalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setMinimumSize(QtCore.QSize(1200, 500))
        self.widget_8.setStyleSheet("border: 1.2px solid rgb(0, 0, 0);\n"
"background-color: rgb(0,0, 0);\n"
"")
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_9.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.widget_8)
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1.2px solid rgb(0, 0, 0);\n"
"")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_10.addWidget(self.textEdit_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setMinimumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border:none;")
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_13.addWidget(self.pushButton_18)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setTabletTracking(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_13.addWidget(self.lineEdit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.verticalLayout_10.addWidget(self.progressBar_2)
        self.verticalLayout_10.setStretch(0, 20)
        self.horizontalLayout_10.addLayout(self.verticalLayout_10)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.horizontalLayout_10.setStretch(1, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1564, 29))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuHelo = QtWidgets.QMenu(self.menubar)
        self.menuHelo.setObjectName("menuHelo")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setCheckable(False)
        self.actionNew.setChecked(False)
        self.actionNew.setEnabled(True)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        self.actionPrint.setObjectName("actionPrint")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExport_data_to_excel = QtWidgets.QAction(MainWindow)
        self.actionExport_data_to_excel.setObjectName("actionExport_data_to_excel")
        self.actionExport_image_file = QtWidgets.QAction(MainWindow)
        self.actionExport_image_file.setObjectName("actionExport_image_file")
        self.actionCoordinate = QtWidgets.QAction(MainWindow)
        self.actionCoordinate.setObjectName("actionCoordinate")
        self.actionLength = QtWidgets.QAction(MainWindow)
        self.actionLength.setObjectName("actionLength")
        self.actionArea = QtWidgets.QAction(MainWindow)
        self.actionArea.setObjectName("actionArea")
        self.actionVTK = QtWidgets.QAction(MainWindow)
        self.actionVTK.setObjectName("actionVTK")
        self.actionOpen3D = QtWidgets.QAction(MainWindow)
        self.actionOpen3D.setObjectName("actionOpen3D")
        self.actionMatplob = QtWidgets.QAction(MainWindow)
        self.actionMatplob.setObjectName("actionMatplob")
        self.actionManualOR = QtWidgets.QAction(MainWindow)
        self.actionManualOR.setObjectName("actionManualOR")
        self.menuSave.addSeparator()
        self.menuSave.addAction(self.actionVTK)
        self.menuSave.addAction(self.actionOpen3D)
        self.menuSave.addAction(self.actionMatplob)
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menuFile.addAction(self.actionExit)
        self.menuTool.addAction(self.actionCoordinate)
        self.menuTool.addAction(self.actionLength)
        self.menuTool.addAction(self.actionArea)
        self.menuTool.addAction(self.actionManualOR)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuHelo.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Parameter"))
        self.pushButton_2.setText(_translate("MainWindow", "Detection"))
        self.pushButton_3.setText(_translate("MainWindow", "Extraction"))
        self.pushButton_4.setText(_translate("MainWindow", "Orientation"))
        self.pushButton_5.setText(_translate("MainWindow", "Measure"))
        self.pushButton_6.setText(_translate("MainWindow", "Save"))
        self.pushButton_14.setText(_translate("MainWindow", "OpShow"))
        self.pushButton_23.setText(_translate("MainWindow", "Input"))
        self.pushButton_24.setText(_translate("MainWindow", "Normal"))
        self.pushButton_25.setText(_translate("MainWindow", "Curvature"))
        self.pushButton_7.setText(_translate("MainWindow", "Input"))
        self.pushButton_8.setText(_translate("MainWindow", "Choose"))
        self.pushButton_9.setText(_translate("MainWindow", "Train"))
        self.pushButton_10.setText(_translate("MainWindow", "Predict"))
        self.pushButton_11.setText(_translate("MainWindow", "Show"))
        self.pushButton_12.setText(_translate("MainWindow", "Extraction"))
        self.pushButton_13.setText(_translate("MainWindow", "Integrate"))
        self.pushButton_15.setText(_translate("MainWindow", "Input"))
        self.pushButton_16.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_22.setText(_translate("MainWindow", "Export"))
        self.pushButton_19.setText(_translate("MainWindow", "Coordinate"))
        self.pushButton_20.setText(_translate("MainWindow", "Length"))
        self.pushButton_21.setText(_translate("MainWindow", "Area"))
        self.pushButton_26.setText(_translate("MainWindow", "ManualOR"))
        self.pushButton_42.setText(_translate("MainWindow", "VTK"))
        self.pushButton_43.setText(_translate("MainWindow", "OPen3D"))
        self.pushButton_44.setText(_translate("MainWindow", "Matplob"))
        self.label.setText(_translate("MainWindow", "Project       "))
        self.label_4.setText(_translate("MainWindow", "Display"))
        self.label_12.setText(_translate("MainWindow", "  Background Color:"))
        self.label_6.setText(_translate("MainWindow", "R"))
        self.label_7.setText(_translate("MainWindow", "G"))
        self.label_8.setText(_translate("MainWindow", "B"))
        self.label_5.setText(_translate("MainWindow", "  Viewing Angle:"))
        self.label_9.setText(_translate("MainWindow", "AA"))
        self.label_10.setText(_translate("MainWindow", "PA"))
        self.checkBox.setText(_translate("MainWindow", "Coordinate Axis"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:16pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:12pt;\"><br /></p></body></html>"))
        self.pushButton_18.setText(_translate("MainWindow", ">>"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.menuHelo.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionImport.setText(_translate("MainWindow", "Import"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExport_data_to_excel.setText(_translate("MainWindow", "Export data to excel"))
        self.actionExport_image_file.setText(_translate("MainWindow", "Export image file"))
        self.actionCoordinate.setText(_translate("MainWindow", "Coordinate"))
        self.actionLength.setText(_translate("MainWindow", "Length"))
        self.actionArea.setText(_translate("MainWindow", "Area"))
        self.actionVTK.setText(_translate("MainWindow", "VTK"))
        self.actionOpen3D.setText(_translate("MainWindow", "Open3D"))
        self.actionMatplob.setText(_translate("MainWindow", "Matplob"))
        self.actionManualOR.setText(_translate("MainWindow", "ManualOR"))
import Catagoty_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
